---
version: 0.2

branches:
  default:
    stage: pre-merge

models:
  - env: &coverage
      CODECOV_TOKEN: '%(secret:codecov_token)s'
      VCS_COMMIT_ID: '%(prop:revision)s'
      VCS_BRANCH_NAME: '%(prop:branch)s'
      CI_BUILD_ID: '%(prop:bootstrap)s'

stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/master
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: true
          retryFetch: true
          haltOnFailure: true
      - ShellCommand:
          name: install dependencies
          command: yarn install --frozen-lockfile
      - ShellCommand:
          name: run lint yml
          command: yarn --silent lint_yml
      - ShellCommand:
          name: run lint
          command: yarn --silent lint --max-warnings 0
      - ShellCommand:
          name: run lint_md
          command: yarn --silent lint_md
      - ShellCommand:
          name: add hostname
          command: sudo sh -c "echo '127.0.0.1 testrequestbucket.localhost' \
            >> /etc/hosts"
      - ShellCommand:
          name: test and coverage
          command: yarn --silent coverage
      - ShellCommand:
          name: upload test coverage
          haltOnFailure: false
          command: "curl -s https://codecov.io/bash | bash"
          env:
            <<: *coverage
      - ShellCommand:
          name: run executables tests
          command: yarn install && yarn test
          workdir: '%(prop:builddir)s/build/lib/executables/pensieveCreds/'
